export const CHANGE_CINEMA_DATA = "CHANGE_CINEMA_DATA";
export const CHANGE_SHOW_DATA = "CHANGE_SHOW_DATA"
export const CHANGE_DEAL_LIST = "CHANGE_DEAL_LIST"
export const CHANGE_VIP_INFO = "CHANGE_VIP_INFO"
export const CHANGE_ADDR = "CHANGE_ADDR"
